### ISSUE TITLE
CNAME gets blown out with force update

### ISSUE THREAD

**Issue by AdamBrodzinski** [middleman-contrib/middleman-deploy#107]
If you're using the force update method to deploy and have created a CNAME file outside of `build/` it will get removed. However if you place it in build you're fine. This should prob. be in the docs?? I'd be happy to PR if that's wanted. 

Also I setup a makefile that ensures it's in place before deploying: `echo 'yourapp.com' > build/CNAME `

Cheers
Adam

**Comment by corroded** [comment]
@AdamBrodzinski can you share your deploy process with this? Did you override the `middleman deploy` command to call the Makefile or do you just run make after you deploy? Doesn't make sense though since it should auto-push to your repo - which means you are running `make` right before you push.

**Comment by AdamBrodzinski** [comment]
@corroded hmmm it's been so long I can't remember. I'll close this as the code has likely changed a lot since then anyway.

**Comment by et** [comment]
I too would be interested in a solution here. I feel like this should be baked into one of the options for the git deployment strategy

```rb
activate :deploy do |deploy|
  deploy.deploy_method = :git
  # Optional Settings
  deploy.cname = 'yourapp.com'
end
```

**Comment by shoshi** [comment]
@et I ended up putting `CNAME` in the `/source` directory instead of in the root folder, and now it gets created in `/build/CNAME` during the build process.
